import type { Application, Neighborhood, Property } from './types';

export const properties: Property[] = [
  {
    id: 'bl001',
    name: '3-bed apartment with sea view',
    type: 'apartment',
    location: {
      area: 'Lekki Phase 1',
      city: 'Lagos',
      landmark: 'Lekki Toll',
      distanceKm: 3.4,
    },
    pricePerYear: 3_200_000,
    serviceCharge: 200_000,
    bedrooms: 3,
    bathrooms: 3,
    sizeSqm: 140,
    furnished: true,
    leaseMonthsMin: 12,
    amenities: ['Borehole', '24/7 power', 'CCTV', 'Parking', 'Security', 'Generator'],
    landlord: {
      name: 'Mr. Adekunle Bello',
      isDirect: true,
      listingsCount: 4,
      avatarTint: '#F5E6D8',
    },
    verifiedAt: '2026-05-12',
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1000&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1000&q=80',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1000&q=80',
    ],
    isFeatured: true,
    description: [
      'A bright, north-facing apartment on the eighth floor with full sea views over the Atlantic. The living area opens onto a 14sqm balcony — wide enough for two armchairs and a small table — and the master bedroom takes the corner of the building.',
      'The kitchen is fully fitted with a gas hob, oven, and built-in fridge. There is a dedicated laundry room with a washing machine connection. Two parking bays are included, both covered.',
      'The building has 24/7 estate security, a backup generator that runs the whole flat, and a treated borehole. Service charge covers waste, security, generator diesel, and common-area maintenance.',
    ],
    nearby: [
      { name: 'Lekki Mall', distanceKm: 2.0 },
      { name: 'Circle Mall', distanceKm: 1.5 },
      { name: 'Lekki Toll', distanceKm: 3.4 },
    ],
    testimonial: {
      quote:
        'We moved in within a week of applying. The landlord was direct and honest, and the lease was already drafted before we asked.',
      author: 'Previous tenant, 2025',
    },
  },
  {
    id: 'bl002',
    name: '4-bed duplex on quiet close',
    type: 'duplex',
    location: {
      area: 'Maitama',
      city: 'Abuja',
      landmark: 'Transcorp Hilton',
      distanceKm: 4.8,
    },
    pricePerYear: 8_500_000,
    serviceCharge: 450_000,
    bedrooms: 4,
    bathrooms: 5,
    sizeSqm: 320,
    furnished: false,
    leaseMonthsMin: 24,
    amenities: ['Borehole', '24/7 power', 'CCTV', 'Parking', 'Security', 'Garden'],
    landlord: {
      name: 'Mrs. Halima Yusuf',
      isDirect: true,
      listingsCount: 2,
      avatarTint: '#E5DFD3',
    },
    verifiedAt: '2026-05-09',
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1000&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1000&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1000&q=80',
    ],
    isFeatured: true,
    description: [
      'A standalone four-bedroom duplex set on a quiet diplomatic close in Maitama. Mature trees front and back, a private compound with space for four cars, and a separate two-room boys quarters at the rear.',
      'All bedrooms are ensuite. The ground floor has a large open-plan living and dining room, a study, a guest WC, and a fitted kitchen with a separate pantry.',
      'C of O verified, lease drafted by our legal partners.',
    ],
    nearby: [
      { name: 'Transcorp Hilton', distanceKm: 4.8 },
      { name: 'Maitama Park', distanceKm: 0.6 },
      { name: 'Wuse Market', distanceKm: 6.1 },
    ],
  },
  {
    id: 'bl003',
    name: 'Self-con studio off Herbert Macaulay',
    type: 'self-con',
    location: {
      area: 'Yaba',
      city: 'Lagos',
      landmark: 'University of Lagos',
      distanceKm: 1.2,
    },
    pricePerYear: 650_000,
    serviceCharge: 50_000,
    bedrooms: 1,
    bathrooms: 1,
    sizeSqm: 32,
    furnished: true,
    leaseMonthsMin: 12,
    amenities: ['Borehole', 'CCTV', 'Security', 'Inverter'],
    landlord: {
      name: 'Mr. Tunde Ogundimu',
      isDirect: true,
      listingsCount: 7,
      avatarTint: '#F5E6D8',
    },
    verifiedAt: '2026-05-14',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1000&q=80',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1000&q=80',
      'https://images.unsplash.com/photo-1574643156929-51fa098b0394?w=1000&q=80',
    ],
    isFeatured: true,
    description: [
      'A compact, well-lit self-contained studio on the second floor of a four-unit block. Quiet, walkable to Unilag, with a small balcony overlooking the rear garden.',
      'Fully furnished: bed, wardrobe, desk, two-burner cooker, fridge, and a working AC. The bathroom is tiled top to bottom with a hot-water heater.',
    ],
    nearby: [
      { name: 'University of Lagos', distanceKm: 1.2 },
      { name: 'Yaba Tech', distanceKm: 1.9 },
      { name: 'Sabo Market', distanceKm: 0.8 },
    ],
  },
  {
    id: 'bl004',
    name: '2-bed flat with balcony',
    type: 'apartment',
    location: {
      area: 'Ikoyi',
      city: 'Lagos',
      landmark: 'Falomo Bridge',
      distanceKm: 1.1,
    },
    pricePerYear: 4_800_000,
    serviceCharge: 300_000,
    bedrooms: 2,
    bathrooms: 2,
    sizeSqm: 110,
    furnished: false,
    leaseMonthsMin: 12,
    amenities: ['Borehole', '24/7 power', 'Lift', 'Parking', 'Security'],
    landlord: {
      name: 'Mr. Olumide Adeyemi',
      isDirect: true,
      listingsCount: 3,
      avatarTint: '#E5DFD3',
    },
    verifiedAt: '2026-05-08',
    images: [
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1000&q=80',
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1000&q=80',
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1000&q=80',
    ],
    isFeatured: false,
    description: [
      'A second-floor two-bedroom flat in a small, well-kept block on a tree-lined Ikoyi street. South-facing living room with a 6sqm balcony.',
    ],
    nearby: [
      { name: 'Falomo Shopping Centre', distanceKm: 0.4 },
      { name: 'Ikoyi Club', distanceKm: 1.2 },
    ],
  },
  {
    id: 'bl005',
    name: 'Bungalow with garden in Bodija',
    type: 'bungalow',
    location: {
      area: 'Bodija',
      city: 'Ibadan',
      landmark: 'University of Ibadan',
      distanceKm: 2.3,
    },
    pricePerYear: 1_400_000,
    serviceCharge: 80_000,
    bedrooms: 3,
    bathrooms: 2,
    sizeSqm: 160,
    furnished: false,
    leaseMonthsMin: 12,
    amenities: ['Borehole', 'Parking', 'Garden', 'Security'],
    landlord: {
      name: 'Mr. Akinwale Ojo',
      isDirect: true,
      listingsCount: 1,
      avatarTint: '#F5E6D8',
    },
    verifiedAt: '2026-05-10',
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1000&q=80',
      'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=1000&q=80',
      'https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=1000&q=80',
    ],
    isFeatured: true,
    description: [
      'A detached three-bedroom bungalow with a wraparound garden in old Bodija. Quiet, mature trees, and just over two kilometres from the University of Ibadan main gate.',
    ],
    nearby: [
      { name: 'University of Ibadan', distanceKm: 2.3 },
      { name: 'Bodija Market', distanceKm: 1.4 },
    ],
  },
  {
    id: 'bl006',
    name: 'Mini-flat near Lekki Conservation',
    type: 'mini-flat',
    location: {
      area: 'Lekki Phase 2',
      city: 'Lagos',
      landmark: 'Lekki Conservation Centre',
      distanceKm: 0.9,
    },
    pricePerYear: 1_100_000,
    serviceCharge: 90_000,
    bedrooms: 1,
    bathrooms: 1,
    sizeSqm: 55,
    furnished: false,
    leaseMonthsMin: 12,
    amenities: ['Borehole', 'CCTV', 'Parking', 'Security'],
    landlord: {
      name: 'Mrs. Funke Aluko',
      isDirect: true,
      listingsCount: 2,
      avatarTint: '#E5DFD3',
    },
    verifiedAt: '2026-05-11',
    images: [
      'https://images.unsplash.com/photo-1505691723518-36a5ac3be353?w=1000&q=80',
      'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=1000&q=80',
      'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=1000&q=80',
    ],
    isFeatured: false,
    description: [
      'A spacious mini-flat in a small, gated block of six. Separate kitchen, large living area, and a single bedroom with built-in wardrobes.',
    ],
    nearby: [
      { name: 'Lekki Conservation Centre', distanceKm: 0.9 },
      { name: 'Chevron Roundabout', distanceKm: 2.2 },
    ],
  },
  {
    id: 'bl007',
    name: '3-bed terrace in Wuse 2',
    type: 'duplex',
    location: {
      area: 'Wuse 2',
      city: 'Abuja',
      landmark: 'Banex Plaza',
      distanceKm: 1.6,
    },
    pricePerYear: 5_400_000,
    serviceCharge: 320_000,
    bedrooms: 3,
    bathrooms: 4,
    sizeSqm: 220,
    furnished: false,
    leaseMonthsMin: 12,
    amenities: ['Borehole', '24/7 power', 'CCTV', 'Parking', 'Security'],
    landlord: {
      name: 'Mr. Ibrahim Sani',
      isDirect: true,
      listingsCount: 5,
      avatarTint: '#F5E6D8',
    },
    verifiedAt: '2026-05-13',
    images: [
      'https://images.unsplash.com/photo-1572120360610-d971b9d7767c?w=1000&q=80',
      'https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?w=1000&q=80',
      'https://images.unsplash.com/photo-1600210492493-0946911123ea?w=1000&q=80',
    ],
    isFeatured: false,
    description: [
      'A three-bedroom terrace in a small estate of eight, with shared 24/7 power and a managed compound. Each unit has its own parking and a small front courtyard.',
    ],
    nearby: [
      { name: 'Banex Plaza', distanceKm: 1.6 },
      { name: 'Jabi Lake', distanceKm: 7.4 },
    ],
  },
  {
    id: 'bl008',
    name: 'Apartment in Jericho GRA',
    type: 'apartment',
    location: {
      area: 'Jericho',
      city: 'Ibadan',
      landmark: 'Jericho Mall',
      distanceKm: 0.7,
    },
    pricePerYear: 1_800_000,
    serviceCharge: 100_000,
    bedrooms: 2,
    bathrooms: 2,
    sizeSqm: 95,
    furnished: true,
    leaseMonthsMin: 12,
    amenities: ['Borehole', 'CCTV', 'Parking', 'Security', 'Generator'],
    landlord: {
      name: 'Mrs. Adebola Lawal',
      isDirect: true,
      listingsCount: 3,
      avatarTint: '#E5DFD3',
    },
    verifiedAt: '2026-05-07',
    images: [
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1000&q=80',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1000&q=80',
      'https://images.unsplash.com/photo-1631679706909-1844bbd07221?w=1000&q=80',
    ],
    isFeatured: false,
    description: [
      'A second-floor two-bedroom flat in a quiet block in old Jericho GRA. Furnished to a high standard, including a fitted kitchen and a working washing machine.',
    ],
    nearby: [
      { name: 'Jericho Mall', distanceKm: 0.7 },
      { name: 'Polo Club', distanceKm: 2.1 },
    ],
  },
  {
    id: 'bl009',
    name: 'Self-con in Surulere',
    type: 'self-con',
    location: {
      area: 'Surulere',
      city: 'Lagos',
      landmark: 'National Stadium',
      distanceKm: 1.8,
    },
    pricePerYear: 500_000,
    serviceCharge: 40_000,
    bedrooms: 1,
    bathrooms: 1,
    sizeSqm: 28,
    furnished: false,
    leaseMonthsMin: 12,
    amenities: ['Borehole', 'Security'],
    landlord: {
      name: 'Mr. Chuka Eze',
      isDirect: true,
      listingsCount: 4,
      avatarTint: '#F5E6D8',
    },
    verifiedAt: '2026-05-15',
    images: [
      'https://images.unsplash.com/photo-1574643156929-51fa098b0394?w=1000&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1000&q=80',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1000&q=80',
    ],
    isFeatured: false,
    description: [
      'A compact self-con on a quiet street near the National Stadium. Independent meter, separate kitchenette area, and tiled throughout.',
    ],
    nearby: [
      { name: 'National Stadium', distanceKm: 1.8 },
      { name: 'Adeniran Ogunsanya Mall', distanceKm: 1.1 },
    ],
  },
  {
    id: 'bl010',
    name: '4-bed duplex in Gwarinpa',
    type: 'duplex',
    location: {
      area: 'Gwarinpa',
      city: 'Abuja',
      landmark: '3rd Avenue Junction',
      distanceKm: 1.3,
    },
    pricePerYear: 4_200_000,
    serviceCharge: 250_000,
    bedrooms: 4,
    bathrooms: 4,
    sizeSqm: 280,
    furnished: false,
    leaseMonthsMin: 12,
    amenities: ['Borehole', '24/7 power', 'CCTV', 'Parking', 'Security', 'Generator'],
    landlord: {
      name: 'Mr. Bashir Aliyu',
      isDirect: true,
      listingsCount: 6,
      avatarTint: '#E5DFD3',
    },
    verifiedAt: '2026-05-06',
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1000&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1000&q=80',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1000&q=80',
    ],
    isFeatured: true,
    description: [
      'A standalone four-bedroom duplex in 3rd Avenue Gwarinpa. All bedrooms ensuite, fitted kitchen, and a small front garden. Backup generator included in service charge.',
    ],
    nearby: [
      { name: '3rd Avenue Junction', distanceKm: 1.3 },
      { name: 'Jabi Lake Mall', distanceKm: 9.2 },
    ],
  },
];

export const neighborhoods: Neighborhood[] = [
  {
    name: 'Lekki Phase 1',
    city: 'Lagos',
    listingCount: 47,
    image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80',
    size: 'large',
  },
  {
    name: 'Yaba',
    city: 'Lagos',
    listingCount: 23,
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80',
    size: 'small',
  },
  {
    name: 'Ikoyi',
    city: 'Lagos',
    listingCount: 31,
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
    size: 'small',
  },
];

export const applications: Application[] = [
  {
    id: 'app-bl001',
    propertyId: 'bl001',
    status: 'inspection-scheduled',
    appliedAt: '2026-05-20',
    reference: 'BL-2026-0512-A7',
    timeline: [
      { label: 'Application received', at: '2026-05-20', done: true },
      { label: 'Documents reviewed', at: '2026-05-21', done: true },
      { label: 'Inspection scheduled', at: '2026-05-24', done: true },
      { label: 'Landlord decision', at: '', done: false },
      { label: 'Lease drafted', at: '', done: false },
    ],
  },
  {
    id: 'app-bl004',
    propertyId: 'bl004',
    status: 'under-review',
    appliedAt: '2026-05-22',
    reference: 'BL-2026-0522-K3',
    timeline: [
      { label: 'Application received', at: '2026-05-22', done: true },
      { label: 'Documents reviewed', at: '', done: false },
      { label: 'Inspection scheduled', at: '', done: false },
      { label: 'Landlord decision', at: '', done: false },
    ],
  },
  {
    id: 'app-bl005',
    propertyId: 'bl005',
    status: 'approved',
    appliedAt: '2026-04-12',
    reference: 'BL-2026-0412-P2',
    timeline: [
      { label: 'Application received', at: '2026-04-12', done: true },
      { label: 'Documents reviewed', at: '2026-04-13', done: true },
      { label: 'Inspection scheduled', at: '2026-04-16', done: true },
      { label: 'Landlord decision', at: '2026-04-20', done: true },
    ],
  },
];

export const savedIds = ['bl002', 'bl005', 'bl008', 'bl010'];

export const findProperty = (id: string) => properties.find((p) => p.id === id);
